version: '2'
services:
  discovery-server:
    image: thuannguyenit/simpleex-discovery-server:smia-05
    ports:
      - "8761:8761"
  config-server:
    image: thuannguyenit/simpleex-config-server:smia-05
    ports:
      - "8888:8888"
    environment:
      DISCOVERYSERVER_URI: "http://discovery-server:8761/eureka/"
      DISCOVERYSERVER_PORT: "8761"
      ENCRYPT_KEY:  "IMSYMMETRIC"
  gateway-server:
    image: thuannguyenit/simpleex-gateway-server:smia-05
    ports:
        - "5555:5555"
    environment:
      PROFILE: "default"
      SERVER_PORT: "5555"
      CONFIGSERVER_URI: "http://config-server:8888"
      DISCOVERYSERVER_URI: "http://discovery-server:8761/eureka/"
      DISCOVERYSERVER_PORT: "8761"
      DATABASESERVER_PORT: "5432"
      CONFIGSERVER_PORT: "8888"
  license-service:
    image: thuannguyenit/simpleex-license-service:smia-05
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: "8080"
      PROFILE: "default"
      CONFIGSERVER_URI: "http://config-server:8888"
      CONFIGSERVER_PORT: "8888"
      DISCOVERYSERVER_URI: "http://discovery-server:8761/eureka/"
      DISCOVERYSERVER_PORT: "8761"
      DATABASESERVER_PORT: "5432"
      ENCRYPT_KEY: "IMSYMMETRIC"
  organization-service:
    image: thuannguyenit/simpleex-organization-service:smia-05
    ports:
      - "8085:8085"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8085"
      CONFIGSERVER_URI: "http://config-server:8888"
      DISCOVERYSERVER_URI: "http://discovery-server:8761/eureka/"
      DISCOVERYSERVER_PORT:   "8761"
      CONFIGSERVER_PORT:   "8888"
      DATABASESERVER_PORT: "5432"
      ENCRYPT_KEY:       "IMSYMMETRIC"
  organization-service2:
      image: thuannguyenit/simpleex-organization-service:smia-05
      ports:
        - "8086:8086"
      environment:
        PROFILE: "default"
        SERVER_PORT: "8086"
        CONFIGSERVER_URI: "http://config-server:8888"
        DISCOVERYSERVER_URI: "http://discovery-server:8761/eureka/"
        DISCOVERYSERVER_PORT:   "8761"
        CONFIGSERVER_PORT:   "8888"
        DATABASESERVER_PORT: "5432"
        ENCRYPT_KEY:       "IMSYMMETRIC"
  database:
    image: postgres:9.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "p0stgr@s"
      POSTGRES_DB: "simple_exchange_local"
    volumes:
      - ../resources/initdb/:/docker-entrypoint-initdb.d/